### ISSUE TITLE
salary tylko int

### ISSUE THREAD

**Issue by bogkra** [bartek56/Students#14]
https://github.com/bartek56/Students/blob/d64e9afd00dd23afbac286a5bf73578161fd445a/users.hpp#L24

wydaje się, że skoro salary jest typu double, to nie powinny się losować tylko liczby całkowite...

**Comment by bartek56** [comment]
salary oczywiście, jako double, lecz to jest losowanie indeksu dla studenta. Czy student ma indeks o wartości dziesiętnej ?
