### ISSUE TITLE
odliczanie od 0

### ISSUE THREAD

**Issue by bogkra** [bartek56/Students#15]
https://github.com/bartek56/Students/blob/d64e9afd00dd23afbac286a5bf73578161fd445a/users.cpp#L49

nie każdy jest programistą c++ i nie każdy zrozumie, dlaczego listę zaczynasz od osoby nr 0... ;)

**Comment by bartek56** [comment]
zastanawiałem się czy zaczynać od 1, ale czy kiedykolwiek programista zaczyna tablice od 1 ? Nie trzeba być programistą C++, żeby o tym wiedzieć. Zamykam issue.
